package com.packtpub.springsecurity.domain.acl;

import java.io.Serializable;
import java.util.Arrays;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.springframework.security.acls.model.ObjectIdentity;

/*
create table acl_object_identity (
  id bigint generated by default as identity(start with 100) not null primary key,
  object_id_class bigint not null,
  object_id_identity bigint not null,
  parent_object bigint,
  owner_sid bigint not null,
  entries_inheriting boolean not null,
  constraint uk_acl_objid unique(object_id_class,object_id_identity),
  constraint fk_acl_obj_parent foreign key(parent_object)references acl_object_identity(id),
  constraint fk_acl_obj_class foreign key(object_id_class)references acl_class(id),
  constraint fk_acl_obj_owner foreign key(owner_sid)references acl_sid(id) );
 */
@Entity
@Table(name="acl_object_identity")
public class AclObjectIdentity implements ObjectIdentity{
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;

    @ManyToOne
    @JoinColumn(name="OBJECT_ID_CLASS")
    private AclClass objIdClass;

    @Column(name="OBJECT_ID_IDENTITY")
    private Long objIdIdentity;

    @ManyToOne
    @JoinColumn(name="PARENT_OBJECT")
    private AclObjectIdentity parentObject;

    @ManyToOne
    @JoinColumn(name="OWNER_SID")
    private AclSid owner;

    @Column(name="ENTRIES_INHERITING")
    private Boolean entriesInheriting;

    @OneToMany(mappedBy="aclObjectIdentity",fetch=FetchType.EAGER)
    private List<AclEntry> aclEntries;

    public List<AclEntry> getAclEntries() {
        return aclEntries;
    }

    public void setAclEntries(List<AclEntry> aclEntries) {
        this.aclEntries = aclEntries;
    }

    public List<AclEntry> getEntries() {
        if(aclEntries!=null) {
            return aclEntries;
        }
        return null;
    }

    public void setEntries(List<AclEntry> entries) {
        this.aclEntries = entries;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public AclClass getObjIdClass() {
        return objIdClass;
    }

    public void setObjIdClass(AclClass objIdClass) {
        this.objIdClass = objIdClass;
    }

    public Long getObjIdIdentity() {
        return objIdIdentity;
    }

    public void setObjIdIdentity(Long objIdIdentity) {
        this.objIdIdentity = objIdIdentity;
    }

    public AclObjectIdentity getParentObject() {
        return parentObject;
    }

    public void setParentObject(AclObjectIdentity parentObject) {
        this.parentObject = parentObject;
    }

    public AclSid getOwner() {
        return owner;
    }

    public void setOwner(AclSid owner) {
        this.owner = owner;
    }

    public Boolean getEntriesInheriting() {
        return entriesInheriting;
    }

    public void setEntriesInheriting(Boolean entriesInheriting) {
        this.entriesInheriting = entriesInheriting;
    }

    @Override
    public Serializable getIdentifier() {

        return this.objIdIdentity;
    }

    @Override
    public String getType() {

        return objIdClass.getClazz();
    }

}
